[graphics]
# Automatische Skalierung auf Bildschirmgröße
fullscreen = auto
multisampling = 1

# Fenster-Setup
window_icon = 
resizable = 1

[input]
# Mouse-Emulation auf Handy (optional)
mouse = mouse

[postproc]
double_tap_time = 667
double_tap_distance = 20

[kivy]
# Hier wird das Log gespeichert
log_level = info
log_dir = /sdcard/kivy_logs
